server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
  tomcat:    max-swallow-size: -1        
    
spring:
  application:
    name: upload-file-service   
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 2MB      
            
                   
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

#El directorio debe crearse en el home del usuario o sección        
nombre_directorio: default 

