server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
  tomcat:
    max-swallow-size: 20971520
    max-http-form-post-size: 20971520

cloud:
  aws:
    credentials:
      access-key: AKIAYIPEKVVPDKAPWBMW
      secret-key: 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
    region:
      static: us-east-2
    stack:
      auto: false

application:
  zuul-server:
    path: http:://localhost:9999/pepeganga/upload/
  buckets:
    products: pepeganga-product-image
    upload: pepeganga-upload-images

logging:
  file:
    name: ./log/upload-file-service.log
    
spring:
  application:
    name: upload-file-service   
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB
            
                   
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://eureka-server:8761/eureka

#El directorio debe crearse en el home del usuario o sección        
nombre_directorio: default

