server:
  port: ${PORT:0}
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
    trust-store: classpath:keystore.p12

spring:
  application:
    name: user-service   
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 123456789.*dhl
    url: jdbc:mysql://db1.cdwhe7xma3dx.us-east-2.rds.amazonaws.com:3306/pepegangadb
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
    nonSecurePortEnabled: false
    securePortEnabled: true
    securePort: ${server.port}
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    secureVirtualHostName: ${spring.application.name}
  client:
    service-url:
        defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: debug