server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  application:
    name: products-service 
  datasource:
    username: admin
    password: 123456789.*dhl  
    url: jdbc:mysql://db-pepeganga-prod.cdwhe7xma3dx.us-east-2.rds.amazonaws.com:3306/pepegangadb
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 5
      minimum-idle: 2
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 33000

#El directorio debe crearse en el home del usuario o sección
risk_time: 5