server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
  
spring:
  application:
    name: products-service 
  datasource:
    username: admin
    password: 123456789.*dhl  
    url: jdbc:mysql://database-homo-prod.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: debug

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
        
#El directorio debe crearse en el home del usuario o sección
risk_time: 5