server:
  port: ${PORT:0}
  
spring:
  application:
    name: products-service   
  datasource:
    username: ####
    password: #### 
    url: ###
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
        
ribbon:
  ConnectTimeout: 3000   
  ReadTimeout: 10000   