server:
  port: ${PORT:0}

spring:
  application:
    name: notification-service
  datasource:
    username: admin
    password: 123456789.*dhl
    url: jdbc:mysql://database-prod.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: debug
  file:
    name: ./log/notification-service.log
