#server:
 # port: ${PORT:0}
 
server:
  port: 9999


spring:
  application:
    name: zuul-service
    

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
        
        
zuul:
  routes:
    user:
      service-id: user-service
      path: /pepeganga/user/**
    products:
        service-id: products-service
        path: /pepeganga/products/**
    oauth:
        service-id: oauth-service
        path: /pepeganga/security/**
        sensitive-headers: Cookie,Set-Cookie

    consuming:
        service-id: consuming-store-service
        path: /pepeganga/consuming/**

hystrix:
   command:
     default:
        execution:
          isolation: 
            thread:
              timeoutInMilliseconds: 350000
ribbon:
   ConnectTimeout: 100000
   ReadTimeout: 150000
