#server:
 # port: ${PORT:0}
 
server:
  port: 9999


spring:
  application:
    name: zuul-service
    

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
        
        
zuul:
  routes:
    user:
      service-id: user-service
      path: /pepeganga/users/**   
    products:
        service-id: products-service
        path: /pepeganga/products/**      
        

hystrix:
   command:
     default:
        execution:
          isolation: 
            thread:
              timeoutInMilliseconds: 20000
ribbon:
   ConnectTimeout: 3000
   ReadTimeout: 10000        
