server:
  port: ${PORT:0}
spring:
  application:
    name: oauth-service
feign:
 client:
   config:
      default:
         connectTimeout: 160000
         readTimeout: 160000

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://eureka-server:8761/eureka
logging:
  file:
    name: ./log/oauth-service.log

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500000
ribbon:
  ConnectTimeout: 100000
  ReadTimeout: 150000