server:
  port: ${PORT:0}
 
spring:
  application:
    name: oauth-service

oauth-service:
  ribbon:
    listOfServers: http://localhost:9999

eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
        defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: debug
