server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: meli-service
  datasource:
    username: admin
    password: 123456789.*dhl
    url: jdbc:mysql://database-prod.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: error
  file:
    name: ./log/meli-service.log

scheduler:
  cron:
    stock: 0 */5 * ? * *
    notification: 0 */3 * ? * *

# Business properties
meli:
  risk: 10
  api:
    url: https://api.mercadolibre.com
    invoice:
      url: https://api.mercadolibre.com/shipment_labels?shipment_ids=XXX&response_type=pdf&access_token=
    client: 3756313271086728
    secret: QjgI9XjbZEd7petHtAVnwFhKpLvnyK6l
    redirect: https://pepeganga-dropshipping.web.app/home/meli-accounts
    expiration:
      token: 30
  order:
    attempts: 3
  hostname:
    free: http://pepeganga-dropshipping.web.app