server:
  port: ${PORT:0}
  error:
    include-message: always
    include-binding-errors: always
spring:
  application:
    name: meli-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: 123456789.*dhl
    #url: jdbc:mysql://db-pepeganga-prod.cdwhe7xma3dx.us-east-2.rds.amazonaws.com:3306/pepegangadb
    url: jdbc:mysql://database-prod.c9ir9n4tc2qb.us-east-2.rds.amazonaws.com:3306/pepegangadb
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  instance:
    instance-id: ${spring.application.name}:${eureka.instance.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
logging:
  level:
    org:
      hibernate:
        SQL: debug

scheduler:
  cron:
    stock: 0 */5 * ? * *
    notification: 0/30 * * ? * *


# Business properties
meli:
  risk: 10
  api:
    url: https://api.mercadolibre.com
    invoice:
      url: https://api.mercadolibre.com/shipment_labels?shipment_ids=XXX&response_type=pdf&access_token=
    client: 5381382874135569
    secret: ach1Wz5swsZTrQVJ9UTdKcAkg1Rsc0UA
    redirect: https://localhost:4200/home/meli-accounts
    expiration:
     token: 30
  order:
    attempts: 1